baseURL: "https://davidbuckley.ca"
languageCode: "en-us"
title: "David Buckley"
theme: "cupper"
params:
  email: "david@davidbuckley.ca"
  customCss:
    - css/code.css # relative path starting from static/
    - css/general.css # relative path starting from static/

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
      unsafe: true

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: About
      url: /about/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5
